"""crear tabla solicitudes_premium

Revision ID: 133ab7bc9611
Revises: 6455c0d52c02
Create Date: 2026-07-03 05:08:43.265048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.infrastructure.config.types


# revision identifiers, used by Alembic.
revision: str = '133ab7bc9611'
down_revision: Union[str, Sequence[str], None] = '6455c0d52c02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_premium',
    sa.Column('id', app.infrastructure.config.types.GUID(length=36), nullable=False),
    sa.Column('personal_id', app.infrastructure.config.types.GUID(length=36), nullable=False),
    sa.Column('numero_cedula', sa.String(length=10), nullable=False),
    sa.Column('nombre_en_cedula', sa.String(length=200), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'aprobada', 'rechazada', name='estado_solicitud'), nullable=False),
    sa.Column('admin_id', app.infrastructure.config.types.GUID(length=36), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['personal_medico.id'], ),
    sa.ForeignKeyConstraint(['personal_id'], ['personal_medico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitudes_premium')
    # ### end Alembic commands ###
