"""Crear tablas iniciales

Revision ID: 3e0d42375f8f
Revises: 
Create Date: 2026-06-30 17:53:47.449120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.infrastructure.config.types


# revision identifiers, used by Alembic.
revision: str = '3e0d42375f8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id', app.infrastructure.config.types.GUID(length=36), nullable=False),
    sa.Column('curp', sa.String(length=18), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('comunidad', sa.String(length=255), nullable=False),
    sa.Column('municipio', sa.String(length=255), nullable=False),
    sa.Column('lengua_materna', sa.String(length=100), nullable=True),
    sa.Column('contacto_emergencia', sa.String(length=255), nullable=True),
    sa.Column('device_generated_id', sa.String(length=36), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_curp'), 'pacientes', ['curp'], unique=True)
    op.create_table('antecedentes_medicos',
    sa.Column('id', app.infrastructure.config.types.GUID(length=36), nullable=False),
    sa.Column('paciente_id', app.infrastructure.config.types.GUID(length=36), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('origen_atencion_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_antecedentes_medicos_paciente_id'), 'antecedentes_medicos', ['paciente_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_antecedentes_medicos_paciente_id'), table_name='antecedentes_medicos')
    op.drop_table('antecedentes_medicos')
    op.drop_index(op.f('ix_pacientes_curp'), table_name='pacientes')
    op.drop_table('pacientes')
    # ### end Alembic commands ###
