"""agregar correo y contrasena_hash a personal_medico

Revision ID: 6455c0d52c02
Revises: e3f692f26483
Create Date: 2026-07-02 03:35:54.115424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6455c0d52c02'
down_revision: Union[str, Sequence[str], None] = 'e3f692f26483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_medico', sa.Column('correo', sa.String(length=255), nullable=False))
    op.add_column('personal_medico', sa.Column('contrasena_hash', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'personal_medico', ['correo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personal_medico', type_='unique')
    op.drop_column('personal_medico', 'contrasena_hash')
    op.drop_column('personal_medico', 'correo')
    # ### end Alembic commands ###
