"""Crear tabla personal_medico

Revision ID: e3f692f26483
Revises: 3e0d42375f8f
Create Date: 2026-06-30 20:10:08.781154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.infrastructure.config.types


# revision identifiers, used by Alembic.
revision: str = 'e3f692f26483'
down_revision: Union[str, Sequence[str], None] = '3e0d42375f8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_medico',
    sa.Column('id', app.infrastructure.config.types.GUID(length=36), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('comunidad', sa.String(length=255), nullable=False),
    sa.Column('municipio', sa.String(length=255), nullable=False),
    sa.Column('cedula_profesional', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_medico')
    # ### end Alembic commands ###
